### PR TITLE
Dev3 into dev

### PR DESCRIPTION
**Pull request by chrispyatt**
Adds all the output and plotting functions + pyvcf parsing to replace line by line stuff

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
general comment, can you go through and update docstrings to add a minimum of parameters and returns (some do describe in the current docstring but laying them out makes it a lot clearer and easier to understand). Also, type hinting is something that can be really useful (especially when debugging or looking back in the future) to remember what inputs / returns are (i.e. is it a list vs a str vs a dataframe etc.)

example:
```
def my func(input1, input2):
    """
    My function does a thing with the first list input1 and adds something to input2, returning modified input2
    """
```

vs

```
def my_func(input1, input2) -> list:
    """
    Takes 2 lists as input, does something to list1 and adds to list2
    Parameters
    ----------
    input1 : list
        a list of things to modifiy
    input2 : list
        a list of things to add modified input1 list to

    Returns
    -------
    list
        input2 list with input1 modified values added
    """
```

This makes it much clearer what is being passed in and returned, and makes it easier to understand what is happening without reading the code. This is an example of numpy/pandas but there's others: https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 7 of 8 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-:-N9HcYbcCjdYWA3PvKX7:btzugbc)* status: 11 of 12 files reviewed, 16 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`FPTP.py` line 225 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HZfMj3ygwBYpaQLLW:-N9HZfMj3ygwBYpaQLLX:bsrotqy) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L225)):*
are you using these elsewhere or just for the variant str below? if so adding anything to an f string automatically converts it to a string:

```
>>> i=1
>>> j=2
>>> f'{i}-{2}'
'1-2'

```
___
*[`FPTP.py` line 228 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9H_0z-8rkheEVqmZ1T:-N9H_0z-8rkheEVqmZ1U:b-iqtbzs) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L228)):*
> ```Python
>             pos = str(record.POS)
>             ref = str(record.REF)
>             # take only alt #1 (should only be one anyway)
> ```

do you have an assert somewhere that checks the VCF has been decomposed so there's no multi allelics present in the same record?
___
*[`FPTP.py` line 249 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9H_E6s3WikVfl5to5M:-N9H_E6s3WikVfl5to5N:bj6w9ff) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L249)):*
this would be better using `isinstance()` to check type:

```
>>> l = [1,2,3]
>>> isinstance(l, list)
True

```



_Code quote:_
```Python
type(val) is list
```
___
*[`FPTP.py` line 255 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HflAiENCTlqUBLrL8:-N9HflAiENCTlqUBLrL9:ba9xala) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L255)):*
this could be better as a dict comprehension to generate a dict:

```
# example data
>>> vcf_format = [1,2,3]
>>> vcf_sample = {1: 'val1', 2:'val2', 3:'val3'}


>>> metric_dict = {f'format_{i}': vcf_sample.get(i) for i in vcf_format}
>>> metric_dict
{'format_1': 'val1', 'format_2': 'val2', 'format_3': 'val3'}

```

n.b. using `.get()` on a dict is better than indexing with `dict[i]` as it will by default return `None` if that value doesn't exist instead of raising a key error, this can also be set to return a default value for missing keys:

```
>>> vcf_format = [1,2,3,4]
>>> vcf_sample = {1: 'val1', 2:'val2', 3:'val3'}

>>> {f'format_{i}': vcf_sample.get(i) for i in vcf_format}
{'format_1': 'val1', 'format_2': 'val2', 'format_3': 'val3', 'format_4': None}

>>> {f'format_{i}': vcf_sample.get(i, 'a_missing_default_value') for i in vcf_format}
{'format_1': 'val1', 'format_2': 'val2', 'format_3': 'val3', 'format_4': 'a_missing_default_value'}

```



_Code quote:_
```Python
            for i in vcf_format:
                name = f'format_{i}'
                value = vcf_sample[i]
                metric_dict[name] = value
```
___
*[`FPTP.py` line 293 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hgdsl-64SXlaObil_:-N9Hgdsl-64SXlaObila:b-13gqfq) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L293)):*
> ```Python
>     Take ref & alt fields, return SNP or INDEL label. Input VCF must be
>     normalised for this method to work (i.e. one variant per position).
>     Possibly redundant as pyvcf has is_SNP or is_Indel methods?
> ```

yeah it does, would use this over doing your own
___
*[`FPTP.py` line 322 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HaJQz3m4e5xXHxkFA:-N9HaJQz3m4e5xXHxkFB:bnj7hl0) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L322)):*
> ```Python
>             # take only alt #1 (should only be one anyway)
>             alt = str(record.ALT[0])
>             variant = (f'{chrom}_{pos}_{ref}_{alt}')
> ```

same as above
___
*[`FPTP.py` line 359 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hgv-sC6cVL-1NSnfP:-N9Hgv-sC6cVL-1NSnfQ:b-kyhu4b) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L359)):*
> ```Python
>     centiles for each value in the input list.
>     '''
>     centiles = []
> ```

list_comp > for loop:

```
centiles = [round(st.percentileofscore(array, i), 2) for i in array]
```



_Code quote:_
```Python
    centiles = []
    for i in array:
        centile = round(st.percentileofscore(array, i), 2)
        centiles.append(centile)
```
___
*[`FPTP.py` line 371 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HhDRG5gBiV5DJivO8:-N9HhDRG5gBiV5DJivO9:b-13kf8i) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L371)):*
> ```Python
>     return plot object.
>     '''
>     label1 = array1.pop(0)
> ```

can you add a comment what this is and why you're using `.pop()`?
___
*[`FPTP.py` line 401 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HanFJ8TvCWzaWXmps:-N9HanFJ8TvCWzaWXmpt:buz4sjr) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L401)):*
> ```Python
>         else:
>             trace['hovertemplate'] = ('<br>Metric value=%{x}<br>Centile=%'
>                                       '{customdata[0]}<br><extra></extra>')
> ```

where you're dropping to a new line its better pep8ness to have a single indent like, especially as things get more indented:

```
trace['hovertemplate'] = (
    '<br>Metric value=%{x}<br>Centile=%{customdata[0]}<br><extra></extra>'
)

```



_Code quote:_
```Python
            trace['hovertemplate'] = ('<br>Metric value=%{x}<br>Centile=%'
                                      '{customdata[0]}<br><extra></extra>')
```
___
*[`FPTP.py` line 415 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HhkjB7ObfmrJNmOV5:-N9HhkjB7ObfmrJNmOV6:b-2i6fp) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L415)):*
first split is redundant I think:
```
>>> s='my-sample-name.vcf.gz'
>>> s.split('.')[0].split('-')[0]
'my'
>>> s.split('-')[0]
'my'
```



_Code quote:_
```Python
sample1 = files[0].split('.')[0].split('-')[0]
```
___
*[`FPTP.py` line 423 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hb7KL85HzmlxJ0fuN:-N9Hb7KL85HzmlxJ0fuO:b3kre) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L423)):*
> ```Python
> def make_html(plots):
>     '''
>     Given a list of plot objects, construct an html report and save to file?
> ```

?



_Code quote:_
```Python
?
```
___
*[`FPTP.py` line 437 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hhxv3-n_cX2pHxv8o:-N9Hhxv3-n_cX2pHxv8p:bdwd8w8) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L437)):*
> ```Python
>                    '<h4>Each metric requested is plotted below, with separate'
>                    ' plots for SNP, INDEL, HET, & HOM variants. Each axis '
>                    'contains a histogram distribution of the metric values for'
> ```

again this can be less indented, only needs to be one tab / 4 spaces



_Code quote:_
```Python
                   f'<html><head><link rel="stylesheet" href="{css}">'
                   '<style>body{{ margin:0 100; background:whitesmoke; }}'
                   '</style><script src="https://cdn.plot.ly/plotly-2.12.1'
                   '.min.js"></script></head><body>'
                   '<h1>QC True/False Positive Distributions</h1>'
                   '<h4>Each metric requested is plotted below, with separate'
                   ' plots for SNP, INDEL, HET, & HOM variants. Each axis '
                   'contains a histogram distribution of the metric values for'
                   ' that group, plus a rug plot along the bottom showing all '
                   'datapoints. Hover over the rug plot to get information'
                   ' about the metric value at that point and the centile that'
                   ' value represents within the data used to generate this '
                   'report.</h4>'
```
___
*[`FPTP.py` line 463 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HbU9o9CZU6OkkJ1b_:-N9HbU9o9CZU6OkkJ1ba:bbgomm9) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L463)):*
> ```Python
>         with open(outfile, 'w') as out:
>             out.write(html_string)
>         return 0
> ```

whats the return for?



_Code quote:_
```Python
return 0
```
___
*[`FPTP.py` line 499 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hk2mW7AUv4K-FaTBW:-N9Hk2mW7AUv4K-FaTBX:b-r3d4ld) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L499)):*
> ```Python
>     '''
>     merged_dict = {}
>     for variant in sample1:
> ```

as above with dict comprehension:

```
merged_dict = {f'SAMPLE1_NAME-{variant}': sample1[variant] for variant in sample1}
```



_Code quote:_
```Python
    merged_dict = {}
    for variant in sample1:
        new_key = SAMPLE1_NAME + '-' + variant
        merged_dict[new_key] = sample1[variant]
```
___
*[`FPTP.py` line 510 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HkqKIE9g1nCwor6rF:-N9HkqKIE9g1nCwor6rG:bb4gswd) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L510)):*
> ```Python
> def make_arrays(data, metric, fptp, snp_indel=None, hethom=None):
>     '''
>     Take merged dictionary, return two arrays (happy vs query, or sample1 vs
> ```

are these actually arrays (i.e. `numpy.array`) vs just a list? Calling lists arrays gets confusing since list and array operations are not the same
___
*[`FPTP.py` line 578 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HbmH09HnfYAtyRUrQ:-N9HbmH1AFbgF6rrPLE4:b-c23av7) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L578)):*
> ```Python
>         hom_plot = create_plot(hom_arrays[0], hom_arrays[1])
>         # make tiled figure with all of the above
>         fig = make_tiled_figure(
> ```

```
 fig = make_tiled_figure(
    [snp_plot, indel_plot, het_plot, hom_plot],
     metric
)

```



_Code quote:_
```Python
        fig = make_tiled_figure(
                                [snp_plot, indel_plot, het_plot, hom_plot],
                                metric
                                )
```

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2)* status: 11 of 12 files reviewed, 16 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`FPTP.py` line 225 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HZfMj3ygwBYpaQLLW:-N9WpNOA3-ZpU77tlcV-:bof2ji0) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L225)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are you using these elsewhere or just for the variant str below? if so adding anything to an f string automatically converts it to a string:

```
>>> i=1
>>> j=2
>>> f'{i}-{2}'
'1-2'

```
</blockquote></details>

got rid of redundant str() for chrom and pos but left it for ref & alt as they're used elsewhere
___
*[`FPTP.py` line 228 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9H_0z-8rkheEVqmZ1T:-N9WAx5iDr6LDOfsTmkn:b-emryii) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L228)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do you have an assert somewhere that checks the VCF has been decomposed so there's no multi allelics present in the same record?
</blockquote></details>

nope, just a note in the readme to say please don't give it multiallelics
___
*[`FPTP.py` line 249 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9H_E6s3WikVfl5to5M:-N9WpWti3IEGT1IodO26:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L249)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this would be better using `isinstance()` to check type:

```
>>> l = [1,2,3]
>>> isinstance(l, list)
True

```
</blockquote></details>

Done.
___
*[`FPTP.py` line 255 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HflAiENCTlqUBLrL8:-N9Wr7umCFVjbNSz8qQU:b-n27625) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L255)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this could be better as a dict comprehension to generate a dict:

```
# example data
>>> vcf_format = [1,2,3]
>>> vcf_sample = {1: 'val1', 2:'val2', 3:'val3'}


>>> metric_dict = {f'format_{i}': vcf_sample.get(i) for i in vcf_format}
>>> metric_dict
{'format_1': 'val1', 'format_2': 'val2', 'format_3': 'val3'}

```

n.b. using `.get()` on a dict is better than indexing with `dict[i]` as it will by default return `None` if that value doesn't exist instead of raising a key error, this can also be set to return a default value for missing keys:

```
>>> vcf_format = [1,2,3,4]
>>> vcf_sample = {1: 'val1', 2:'val2', 3:'val3'}

>>> {f'format_{i}': vcf_sample.get(i) for i in vcf_format}
{'format_1': 'val1', 'format_2': 'val2', 'format_3': 'val3', 'format_4': None}

>>> {f'format_{i}': vcf_sample.get(i, 'a_missing_default_value') for i in vcf_format}
{'format_1': 'val1', 'format_2': 'val2', 'format_3': 'val3', 'format_4': 'a_missing_default_value'}

```
</blockquote></details>

this will overwrite the metric_dict already started for the info metrics though, right? So I need to change this to add to metric_dict rather than assign the output of the dict comp to the metric_dict variable? Is using dict.update() ok for this?
___
*[`FPTP.py` line 293 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hgdsl-64SXlaObil_:-N9WsQ3o6gY3k1SBxtDS:bmmtgn) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L293)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

yeah it does, would use this over doing your own
</blockquote></details>

I'm going to leave this as is for now, just because the 2 sample functionality isn't implemented in the tool yet so this function is never actually called. But I'll add a note to change it when I add that functionality.
___
*[`FPTP.py` line 322 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HaJQz3m4e5xXHxkFA:-N9WsvDG4XPNzGZy9JPm:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L322)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[`FPTP.py` line 359 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hgv-sC6cVL-1NSnfP:-N9X77TkDOYnyh9F-lJ2:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L359)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

list_comp > for loop:

```
centiles = [round(st.percentileofscore(array, i), 2) for i in array]
```
</blockquote></details>

Done.
___
*[`FPTP.py` line 371 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HhDRG5gBiV5DJivO8:-N9X7emz9507kRQ8SG9m:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L371)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add a comment what this is and why you're using `.pop()`?
</blockquote></details>

Done.
___
*[`FPTP.py` line 401 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HanFJ8TvCWzaWXmps:-N9X9vJhBV3qWPgSeMPF:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L401)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

where you're dropping to a new line its better pep8ness to have a single indent like, especially as things get more indented:

```
trace['hovertemplate'] = (
    '<br>Metric value=%{x}<br>Centile=%{customdata[0]}<br><extra></extra>'
)

```
</blockquote></details>

Done.
___
*[`FPTP.py` line 415 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HhkjB7ObfmrJNmOV5:-N9XImuf43HOXXFZIyeT:b-tn0f53) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L415)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

first split is redundant I think:
```
>>> s='my-sample-name.vcf.gz'
>>> s.split('.')[0].split('-')[0]
'my'
>>> s.split('-')[0]
'my'
```
</blockquote></details>

fair point
___
*[`FPTP.py` line 423 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hb7KL85HzmlxJ0fuN:-N9XJvsv6DHU9XYTLY5K:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L423)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`FPTP.py` line 437 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hhxv3-n_cX2pHxv8o:-N9XKA4KEjWkmnR7HW-K:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L437)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

again this can be less indented, only needs to be one tab / 4 spaces
</blockquote></details>

Done.
___
*[`FPTP.py` line 463 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HbU9o9CZU6OkkJ1b_:-N9XKcU-775Jb2M--csK:b-hiqn2z) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L463)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

whats the return for?
</blockquote></details>

easy way to test it hasn't failed? Although I guess I could do that the other way around with the except bit
___
*[`FPTP.py` line 499 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hk2mW7AUv4K-FaTBW:-N9XNUfd48xAPrZDuEwc:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L499)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

as above with dict comprehension:

```
merged_dict = {f'SAMPLE1_NAME-{variant}': sample1[variant] for variant in sample1}
```
</blockquote></details>

Done.
___
*[`FPTP.py` line 510 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HkqKIE9g1nCwor6rF:-N9XNJ7f5cmasriuCnZJ:b8qq4f7) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L510)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are these actually arrays (i.e. `numpy.array`) vs just a list? Calling lists arrays gets confusing since list and array operations are not the same
</blockquote></details>

no I just changed the way I did the plots but got lazy with the function/variable names. Have changed now.
___
*[`FPTP.py` line 578 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HbmH09HnfYAtyRUrQ:-N9XNbqt539k-1KktCUs:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L578)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

```
 fig = make_tiled_figure(
    [snp_plot, indel_plot, het_plot, hom_plot],
     metric
)

```
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[`FPTP.py` line 228 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9H_0z-8rkheEVqmZ1T:-N9bEp-oA71kyWZWhMXK:bhxu9nu) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L228)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

nope, just a note in the readme to say please don't give it multiallelics
</blockquote></details>

I think it would be good to check as you're reading records that there's none present so the output is correct, even if its just a simple assert like `assert len(record.ALT) == 1, 'multi allelic variant found'`
___
*[`FPTP.py` line 255 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HflAiENCTlqUBLrL8:-N9bDXcC-AmsIHc3pjf8:b-yug6g4) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L255)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

this will overwrite the metric_dict already started for the info metrics though, right? So I need to change this to add to metric_dict rather than assign the output of the dict comp to the metric_dict variable? Is using dict.update() ok for this?
</blockquote></details>

yep, looks good
___
*[`FPTP.py` line 293 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hgdsl-64SXlaObil_:-N9bE-cp-EyvP0LZEbFd:b-qkv01n) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L293)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

I'm going to leave this as is for now, just because the 2 sample functionality isn't implemented in the tool yet so this function is never actually called. But I'll add a note to change it when I add that functionality.
</blockquote></details>

for things like this where it is for future you to remember its good to add TODO comments, then you can scan through code to find unfinished things to work on (i.e. `TODO: implement this function for 2 sample comparisons`)

**Review by chrispyatt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`FPTP.py` line 228 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9H_0z-8rkheEVqmZ1T:-N9gFrY67T_qIZQLLHpk:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L228)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I think it would be good to check as you're reading records that there's none present so the output is correct, even if its just a simple assert like `assert len(record.ALT) == 1, 'multi allelic variant found'`
</blockquote></details>

Done.
___
*[`FPTP.py` line 255 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9HflAiENCTlqUBLrL8:-N9fzORS295UxclGXMSh:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L255)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

yep, looks good
</blockquote></details>

Done.
___
*[`FPTP.py` line 293 at r8](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-N9Hgdsl-64SXlaObil_:-N9gFdO4CnSanSnoBg3Z:b-896fix) ([raw file](https://github.com/eastgenomics/confirmationthresholds/blob/544d4370c752865551d0efb9bdf715f1de3bb54e/FPTP.py#L293)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

for things like this where it is for future you to remember its good to add TODO comments, then you can scan through code to find unfinished things to work on (i.e. `TODO: implement this function for 2 sample comparisons`) 
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2#-:-N9gLKBg6tPdkAd_7Qja:bnfp4nl)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @jethror1 and @mattgarner)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/confirmationthresholds/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Pull request merged**
